meta_product_name: "Nubi"
meta_title: "Nubi | Smoother onboarding experience"
meta_description: "Make your new employees' beginning smoother than ever before"
meta_type: "website"
meta_url: "https://www.nubiapp.co/"
# If your image has the following dimensions: 1200x630, test will pass.
meta_image: "logo.png" # should exist in `app/assets/images/`
